[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@1inch/=lib/solidity-utils/contracts/",
    "limit-order-protocol-contract/=lib/limit-order-protocol/contracts/",
    "cross-chain-swap/=../../cross-chain-swap/contracts/",
    "solidity-utils/=lib/solidity-utils/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
